// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQwRvAxJ9SIfDxKJNQyWCowbzBBOEieA',
    appId: '1:1088558635713:web:4a8b06f5a58d5fb7059240',
    messagingSenderId: '1088558635713',
    projectId: 'flox-builder',
    authDomain: 'flox-builder.firebaseapp.com',
    storageBucket: 'flox-builder.firebasestorage.app',
    measurementId: 'G-MT5LCJ4XBX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2MTYcwlJqdNef3RARfuxz7E8xXvmqA4',
    appId: '1:1088558635713:ios:771b0917bc702ff1059240',
    messagingSenderId: '1088558635713',
    projectId: 'flox-builder',
    storageBucket: 'flox-builder.firebasestorage.app',
    iosBundleId: 'com.floxuz.flox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuQwRvAxJ9SIfDxKJNQyWCowbzBBOEieA',
    appId: '1:1088558635713:web:812668054f55a6a3059240',
    messagingSenderId: '1088558635713',
    projectId: 'flox-builder',
    authDomain: 'flox-builder.firebaseapp.com',
    storageBucket: 'flox-builder.firebasestorage.app',
    measurementId: 'G-146MG85G98',
  );
}
